# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: python:3.7

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'which locale-gen || (apt update -y && apt install locales -y)'
    # for fr_FR.UTF-8
    # - sed -i -e 's/# fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
    - sed -i -e 's/# fr_FR /fr_FR /' /etc/locale.gen && locale-gen
    - ./scripts/build.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - output/
  only:
    refs:
      - master

deploy:
  stage: deploy
  environment:
    name: production
  only:
    refs:
      - master
  script:
    - mv output htdocs
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which make || ( apt-get update -y && apt-get install make -y )'
    - 'which lftp || ( apt-get update -y && apt-get install lftp -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$PRIVATE_SSH_KEY")
    - make ftp_upload
