# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: python:3.7

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make publish
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - output/
  only:
    refs:
      - master


deploy:
  stage: deploy
  environment:
    name: production
  only:
    refs:
      - master
  script:
    - git checkout --orphan production
    - mv output htdocs
    - git add htdocs
    - git commit -m "Publishing"
    - git remote add gandi ${GIT_URL}/blog.mlcdf.com
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$PRIVATE_SSH_KEY")
    - git push gandi production
    - ssh ${GIT_URL} 'deploy blog.mlcdf.com.git'
