name: "mlcdf"
description: "Maxime Le Conte des Floris is a web developer."
author: "mlcdf"
url: "https://mlcdf.com"
future: true
exclude: [README.md, Rakefile, node_modules]
#paginate: 5
permalink: pretty
# highlighter: pygments
