[build]
  command = "./scripts/publish.sh"
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.7"

[[headers]]
  for = "/*"
    [headers.values]
    	Cache-Control = "no-cache"
      X-Content-Type-Options = "nosniff"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
      Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
    [headers.values]
      Content-Security-Policy = "default-src 'self'"
      Cache-Control = "must-revalidate, max-age=600"

[[headers]]
  for = "*.css, *.woff, *woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

[context.production.environment]
  SITEURL = "https://blog.mlcdf.fr"

[context.dev.environment]
  SITEURL = "/"
