[build]
  command = "./scripts/publish.sh"
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.7"

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "*.css" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[context.production.environment]
  SITEURL = "https://blog.mlcdf.fr"

[context.dev.environment]
  SITEURL = "/"
