name: Build website

on:
  push:
    branches:
      - 'blog'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mlcdf/blog:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Build website
        run: |
          ./scripts/publish.sh

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: /website # or path/to/artifact

  deploy:
    runs-on: ubuntu-latest
    container:
      image: rclone/rclone
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          
      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy
        run: |
          export RCLONE_CONFIG_MYS3_ACCESS_KEY_ID=$CELLAR_ADDON_KEY_ID
          export RCLONE_CONFIG_MYS3_SECRET_ACCESS_KEY=$CELLAR_ADDON_KEY_SECRET
          export RCLONE_CONFIG_MYS3_ENDPOINT=$CELLAR_ADDON_HOST
          export RCLONE_CONFIG_MYS3_TYPE="s3"

          # Sync the site to Cellar
          rclone sync . mys3:$MY_DOMAIN --progress --s3-acl=public-read