name: Build website

on:
  push:
    branches:
      - 'blog'

jobs:
  docker:
    runs-on:  ubuntu-latest
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website
        run: |
          docker pull ghcr.io/mlcdf/blog:latest
          docker run \
            -t ghcr.io/mlcdf/blog:latest \
            -v "$(pwd)"/target:/website

      - name: Deploy the website
        run |
          docker pull rclone/rclone

