name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - 'blog'
      - 'dev'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/mlcdf/blog:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/mlcdf/blog:buildcache
          cache-to: type=registry,ref=ghcr.io/mlcdf/blog:buildcache,mode=max

  build-and-deploy-website:
    needs: build-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mlcdf/blog:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy website
        env:
          SITEURL: ${{ secrets.SITEURL }}
          KEY: ${{ secrets.KEY }}
          RCLONE_CONFIG_CELLAR_ENDPOINT: ${{ secrets.RCLONE_CONFIG_CELLAR_ENDPOINT }}
          RCLONE_CONFIG_CELLAR_ACCESS_KEY_ID: ${{ secrets.RCLONE_CONFIG_CELLAR_ACCESS_KEY_ID }}
          RCLONE_CONFIG_CELLAR_SECRET_ACCESS_KEY: ${{ secrets.RCLONE_CONFIG_CELLAR_SECRET_ACCESS_KEY }}
        run: |
          ./scripts/publish.sh $SITEURL
